image: continuumio/miniconda3:4.7.12

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - conda env create --file environment.yml
  - source activate aileen

test:
  script:
    - pytest --pyargs tests
