image: continuumio/miniconda3:4.7.12

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python2 --version
  - ./bootstrap.sh
  - source activate aileen

test:
  script:
    - pytest --pyargs tests
