image: aaronang/conda-pynini:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - ./bootstrap.sh
  - source activate aileen
  - python -m easy_install /opt/conda/lib/python2.7/site-packages/pynini-1.9.3-py2.7-linux-x86_64.egg

test:
  script:
    - pytest --pyargs tests
