name: aileen
# channels:
#   - conda-forge
#   - marufr
#   - menpo
dependencies:
  - python=2.7
  - seaborn
  - scikit-learn
  - pandas
  - torchvision
  - matplotlib
  - coloredlogs
  # - enum
  - typing
  - numpy
  - pyyaml
  - yaml
  - shapely
  - pytest
  - marufr::python-igraph
  - opencv
  - psutil
  - pip
  - pip:
      - imutils
      - enum
      - inflect
      - -e strands_qsr_lib/qsr_lib/
      - agent/vision/
      - -e .
      - ikpy==3.0
