## co-ordinates in AILEEN world

OBJECT_POSITION_MAX_X = 0.855
OBJECT_POSITION_MIN_X = 0.356

OBJECT_POSITION_MAX_Y = 0.45
OBJECT_POSITION_MIN_Y = 0.45

OBJECT_POSITION_MAX_Z = 0.242
OBJECT_POSITION_MIN_Z = -0.245

OBJECT_STANDARD_HEIGHT = 0.1
OBJECT_STANDARD_WIDTH_X = 0.1
OBJECT_STANDARD_WIDTH_Z = 0.1


SHAPE_SET = ['cone', 'box', 'cylinder', 'sphere']

COLOR_FILE_NAME = 'colors.json'


SPATIAL_CONFIGURATION_FILE_NAME = 'spatial_configuration.json'
SPATIAL_DEF_OBJECTS = 'objects'
SPATIAL_DEF_DEFINITION = 'definition'
SPATIAL_DEF_LANGUAGE_TEMPLATE = 'language'



ACTION_DEFINITION_FILE_NAME = 'action_definition.json'
ACTION_DEF_OBJECTS = 'objects'
ACTION_DEF_RELATIONS = 'relations'
ACTION_DEF_INIT_CONFIG = 'initial_configuration'
ACTION_DEF_TRACE_ACTIONS = 'trace-actions'
ACTION_DEF_LANGUAGE = 'language'



ACTION_LESSON_STATE_START = 'start'
ACTION_LESSON_STATE_TRACE = 'trace'
ACTION_LESSON_STATE_END = 'end'
ACTION_LESSON_STATE_COMPLETE = 'complete'
ACTION_LESSON_STATE_BAD = 'bad'

# Vision training script parameters
TRAINING_DATA_FOLDER = './vision_training_data'
TRAIN_FILES = TRAINING_DATA_FOLDER + '/train_files.txt'
TEST_FILES = TRAINING_DATA_FOLDER + '/test_files.txt'
